name: Build ATJ Firmware Tool - Windows (MinGW)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows-mingw:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Install MinGW-w64
      run: choco install mingw -y --no-progress
      shell: pwsh # 使用PowerShell

    - name: Add MinGW to PATH
      run: |
        $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        echo "::add-path::$mingwPath"
      shell: pwsh

    - name: Create Build Directory
      run: mkdir build

    - name: Configure with CMake for MinGW
      run: |
        cmake -B build -S . `
          -G "MinGW Makefiles" `
          -DCMAKE_BUILD_TYPE=Release
      shell: pwsh

    - name: Build Project
      run: cmake --build build --config Release --parallel
      shell: pwsh

    - name: List Build Artifacts
      run: Get-ChildItem build -Filter *.exe -Name
      shell: pwsh

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: atj-firmware-tool-windows-mingw
        path: build\*.exe
        if-no-files-found: error
